destination: ./_site
port: 4000
markdown: redcarpet
permalink: date
highlighter: pygments

github_username: numberoverzero
feedburner: numberoverzero
email: joe.mcross@gmail.com

gems:
  - jekyll-sitemap
