destination: ./_site
port: 4000
markdown: redcarpet
permalink: date
pygments: true
banner: hero.png

twitter: numberoverzero
linkedin: numberoverzero
github: numberoverzero
email: joe.mcross@gmail.com
